---
apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: general
spec:
  forProvider:
    clusterNameRef:
      name: dev-stage
    nodeRoleArnRef:
      name: dev-stage-eks-nodes
    region: eu-west-3
    capacityType: ON_DEMAND
    instanceTypes: ["t3.small"]
    labels:
      role: general
    scalingConfig:
      - desiredSize: 1
        minSize: 1
        maxSize: 10
    subnetIdRefs:
      - name: dev-private-eu-west-3a
      - name: dev-private-eu-west-3b
---
apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: spot
spec:
  forProvider:
    clusterNameRef:
      name: dev-stage
    nodeRoleArnRef:
      name: dev-stage-eks-nodes
    region: eu-west-3
    capacityType: SPOT
    instanceTypes: ["t3.small"]
    labels:
      role: spot
    taint:
      - key: type
        value: spot
        effect: NO_SCHEDULE
    scalingConfig:
      - desiredSize: 1
        minSize: 1
        maxSize: 10
    subnetIdRefs:
      - name: dev-private-eu-west-3a
      - name: dev-private-eu-west-3b